### ISSUE TITLE
[Feature Request] Comfort in updating values

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#1]
![image](https://user-images.githubusercontent.com/63019821/116954070-50ab2580-ac65-11eb-8a08-c00f5595203a.png)

When clicking (where it is selected in the image) and making changes in the text box, the "update" button should work, updating the values.

(it's a little annoying to click on the + all the time to update value), this is more to make life easier, select and change.

**Comment by OniSensei** [comment]
Added! Will be in next release.
![Update without +](https://imgur.com/3DJgMsh.gif)
