### ISSUE TITLE
[Report] Wrong tip

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#10]
![image](https://user-images.githubusercontent.com/63019821/117553437-0d1b3780-b028-11eb-9bb5-bad72df3df73.png)

All options in the json, which involves colors (textcolor, rendercolor, etc.) the right order is ARGB, alpha, red, green, blue.

**Comment by WeylonSantana** [comment]
![image](https://user-images.githubusercontent.com/63019821/117553492-55d2f080-b028-11eb-9366-6d5dd417d96e.png)
All the tips below this option are with the color tip

edit: forget my mistake, by clicking on an option with a tip and after, click on any of these will continue with the same tip, maybe that's because there is no tip to show and then show the last one

**Comment by OniSensei** [comment]
Fixed both the wrong order of argb and the hint not clearing when selecting a value without a hint. Will be in next update.
