### ISSUE TITLE
[Feature Request] Shortcuts

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#12]
To make the whole process faster there could be shortcuts

Ctrl + S = save the json file
Enter = "update"

When a person makes a change in that area
![image](https://user-images.githubusercontent.com/63019821/117553958-0215d680-b02b-11eb-97b4-5339deff1b5b.png)

the enter button is not necessary, in any json file on the gui, so to avoid this
![image](https://user-images.githubusercontent.com/63019821/117553984-31c4de80-b02b-11eb-9028-5bd5195bc41a.png)
the "enter" could be "disabled" and press it, an "update" could be executed

its good even at changing files,
change value, enter, change value, enter, change value, enter, etc ...

**Comment by OniSensei** [comment]
Added. Will be in next release.
