### ISSUE TITLE
[Feature Request] Continuity

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#5]
![image](https://user-images.githubusercontent.com/63019821/116955270-72f27280-ac68-11eb-9f7f-2408628cb3b9.png)

Another thing to make life easier.
When we are changing a value, it would be good if the value continues to be shown in this box (from the image above), because many times we have to change the value several times, from 5 out of 5, 10 out of 10, until we find the perfect value. So clicking update and clicking the +, and the value, several times, would make the process boring.

Also annoying in the standard way, changing the value in json and resizing the client window so that the values are loader.

**Comment by OniSensei** [comment]
Added - will be in next release.
