### ISSUE TITLE
[Feature Request] Text Editor

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#6]
I saw that there is a tab, text, where it shows the json file content
It would be nice if there could be the possibility to edit that area within your program and see the changes with the update button in the editor.

Like, I am more accommodated with the files so for me, I'll save time editing there, than using the "tree" tab. Because I know where each line is that I need to edit

**Comment by OniSensei** [comment]
Added - will be in next release
