### ISSUE TITLE
[Bug] Error

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#7]
![image](https://user-images.githubusercontent.com/63019821/116956432-a5ea3580-ac6b-11eb-86f1-6d03045421db.png)

I tried to put a custom gui of mine

I deleted your gui folder
I put mine

tried to open playerbox

the error appeared

[Log.txt](https://github.com/OniSensei/Intersect-GUI-Editor/files/6418827/Log.txt)
The language in this text file is Portuguese from Brazil, if you need to use google translator

**Comment by OniSensei** [comment]
This error is referencing a line that calls on the PlayerBox.json to load the `Children.EntityInfoPanel.Texture`
This means it can't find the file under the `Texture` section of the `EntityInfoPanel` section. See referenced image.
![Image of PlayerBox.json](https://imgur.com/HxqxpWG.png)

There will be checks in the future for Null values and settings in the future for example, if your `entitybox.png` is under the `Texture` of the main `PlayerBox` panel and not the `EntityInfoPanel`.

**Comment by WeylonSantana** [comment]
I will wait for these future checks then.
