### ISSUE TITLE
[Bug] Bad Elements

### ISSUE THREAD

**Issue by WeylonSantana** [OniSensei/Intersect-GUI-Editor#8]
![image](https://user-images.githubusercontent.com/63019821/116956672-3759a780-ac6c-11eb-9502-a12021976817.png)

Some things are not loadign in the place they should, I use for example more than 5 slots, and they do not appear, each slot has its own image inside the gui folder

![image](https://user-images.githubusercontent.com/63019821/116956779-83a4e780-ac6c-11eb-9e98-2792e67d553a.png)

**Comment by OniSensei** [comment]
This is due to the application only loading the default Intersect panels for the character screen. There will be a future update that will support minor edits like this to the Json files.

Suggest you add this as a feature request rather than a bug. 

Thanks.
